[project]
name = "services"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bilibili-api-python>=17.1.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
